import { createStore } from 'vuex' 

export default createStore({
    state: {
        message: "USER!",
        is_expanded: false,
        isMenuOpen: false,
        cssPopUpEmerDetail: false,
        wellness:[
            {
                id:"3542",
                congenitalDisease:[],
                doctor:[],
                startDate:"",
                status:[
                    {   
                        nameStatus:"mmHg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"107/70"
                    },
                    {   
                        nameStatus:"BPM",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"94"
                    },
                    {   
                        nameStatus:"oxygen",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"99"
                    },
                    {   
                        nameStatus:"mg/dl",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"150"
                    },
                    {   
                        nameStatus:"temp",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"36"
                    },
                    {   
                        nameStatus:"kg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"66"
                    },
                ]
            },
            {
                id:"2345",
                congenitalDisease:[],
                doctor:[],
                startDate:"",
                status:[
                    {   
                        nameStatus:"mmHg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"107/70"
                    },
                    {   
                        nameStatus:"BPM",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"94"
                    },
                    {   
                        nameStatus:"oxygen",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"99"
                    },
                    {   
                        nameStatus:"mg/dl",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"150"
                    },
                    {   
                        nameStatus:"temp",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"36"
                    },
                    {   
                        nameStatus:"kg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"66"
                    },
                ]
            },
            {
                id:"3542",
                congenitalDisease:[],
                doctor:[],
                startDate:"",
                status:[
                    {   
                        nameStatus:"mmHg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"107/70"
                    },
                    {   
                        nameStatus:"BPM",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"94"
                    },
                    {   
                        nameStatus:"oxygen",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"99"
                    },
                    {   
                        nameStatus:"mg/dl",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"150"
                    },
                    {   
                        nameStatus:"temp",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"36"
                    },
                    {   
                        nameStatus:"kg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"66"
                    },
                ]
            },
            {
                id:"5645",
                congenitalDisease:[],
                doctor:[],
                startDate:"",
                status:[
                    {   
                        nameStatus:"mmHg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"107/70"
                    },
                    {   
                        nameStatus:"BPM",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"94"
                    },
                    {   
                        nameStatus:"oxygen",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"99"
                    },
                    {   
                        nameStatus:"mg/dl",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"150"
                    },
                    {   
                        nameStatus:"temp",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"36"
                    },
                    {   
                        nameStatus:"kg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"66"
                    },
                ]
            },
            {
                id:"2345",
                congenitalDisease:[],
                doctor:[],
                startDate:"",
                status:[
                    {   
                        nameStatus:"mmHg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"107/70"
                    },
                    {   
                        nameStatus:"BPM",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"94"
                    },
                    {   
                        nameStatus:"oxygen",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"99"
                    },
                    {   
                        nameStatus:"mg/dl",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"150"
                    },
                    {   
                        nameStatus:"temp",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"36"
                    },
                    {   
                        nameStatus:"kg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"66"
                    },
                ]
            },
            {
                id:"1574",
                congenitalDisease:[],
                doctor:[],
                startDate:"",
                status:[
                    {   
                        nameStatus:"mmHg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"107/70"
                    },
                    {   
                        nameStatus:"BPM",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"94"
                    },
                    {   
                        nameStatus:"oxygen",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"99"
                    },
                    {   
                        nameStatus:"mg/dl",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"150"
                    },
                    {   
                        nameStatus:"temp",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"36"
                    },
                    {   
                        nameStatus:"kg",
                        isStatus:true,
                        statusDesc:"ความดันโลหิตผิดปกติ",
                        value:"66"
                    },
                ]
            },
            
        ]
    },
    mutations:{
        haddleMenu(state){
            if(state.isMenuOpen === false){
                state.setmenu = "open setmenu"
                state.setsidemenu = "isopen-set-menu-container"
                state.cssGoogleMapContainer = "bind-set-googlemap-container"
                state.isMenuOpen = true

            }else{
                state.setmenu = "setmenu"
                state.setsidemenu = "set-menu-container"
                state.cssGoogleMapContainer = "set-googlemap-container"
                state.isMenuOpen = false
            }

        },
    }
  })

